services:
  chatgpt-register-web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: chatgpt-register-web
    restart: unless-stopped
    network_mode: host
    env_file:
      - .env
    volumes:
      - ./config.json:/app/config.json:Z
      - ./registered_accounts.txt:/app/registered_accounts.txt:Z
      - ./ak.txt:/app/ak.txt:Z
      - ./rk.txt:/app/rk.txt:Z
      - ./codex_tokens:/app/codex_tokens:Z
      - ./zhuce5_cfmail_accounts.json:/app/zhuce5_cfmail_accounts.json:Z
